### ISSUE TITLE
it's not a bag, I just have a question 

### ISSUE THREAD

**Issue by olehmysticgames** [VergilUa/EntitiesExt#2]
hello, thank you very much for the solution to sync Entity&Mono.

I am implementing a projectile moving via your solution, and when a projectile hit an enemy I want to add a "HitComponent" to the entity to play particles and push the bullet MonoBehaviour to an object pool, Maybe you can suggest how better notify MonoBehaviour that a new component has been added to its Entity?

**Comment by VergilUa** [comment]
Hi, if you're using system to alter state, simplest solution would be to add actual MonoBehaviour to the entity. And then use system to notify the behaviour. Also, make sure to put managed system into AfterSimulationGroup to avoid job stalls.
1. Depending on whether its IEntityManagedSupplier or IEntitySupplier, you can do add it in SetupEntity:
```entityManager.Add(entity, this)``` [equivalent to EntityManager.AddComponentObject(entity, *UnityEngine.Object*)]
or call via
```_entityBehaviour.Add(this)```

2. Add tag component to the entity by any means
3. Then via managed [SystemBase] system you can query that component directly and do whatever needed. 
E.g. via EFE:

```
Entities.ForEach((in SomeBehaviour behaviour) => behaviour.DoSomething())
    .WithAll<HitComponent>()
    .WithStructuralChanges() // Probably will be required if you're altering Entity state via DoSomething
    .WithoutBurst()
    .Run();
```

**Comment by olehmysticgames** [comment]
wow, thank you very much for the quick response. I was thinking to make in a kinda way, but was curious if there is any other solution

**Comment by VergilUa** [comment]
> wow, thank you very much for the quick response. I was thinking to make in a kinda way, but was curious if there is any other solution

No problem. 
When working with entities its easier to treat MonoBehaviours (or any UnityEngine.Object) as authoring / data only component (or as a managed callback) and move actual logic to the systems. Easier to maintain code this way.
