### ISSUE TITLE
Add package.json to support installing via OpenUPM

### ISSUE THREAD

**Issue by laicasaane** [VergilUa/EntitiesExt#3]
Hi, I usually avoid importing packages directly into my project. Please add a `package.json` file to both EntitiesEx and HybridTransformations folders so we can register them on OpenUPM service. Thanks!

**Comment by VergilUa** [comment]
Hi, HybridTransformations requires EntitiesExt as a dependency. Even without extensions, systems rely on custom ECB systems for proper ordering. EntitiesExt as a separate package should work though. 

In any case, I'll look into it.

**Comment by VergilUa** [comment]
Base package name - com.nightphoxen.entitiesext;
HybridTransformations - com.nightphoxen.hybridtransformations 
(includes EntitiesExt as dependency automatically);

Tested adding both, should be available now. 
Just in case, badges with respective links are also available on the main repo page.
